# Generated by Django 4.2.1 on 2024-01-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guild", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="all_information",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Фото",
            ),
        ),
    ]
