# Generated by Django 4.2.1 on 2024-01-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guild", "0002_all_information_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="all_information",
            name="link",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ссылки"),
        ),
    ]
