# Generated by Django 4.2.1 on 2024-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guild", "0003_all_information_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_information",
            name="link",
            field=models.TextField(blank=True, max_length=255, verbose_name="Ссылки"),
        ),
    ]
